#define NOTHING 0
#define LMCOORD 1
#define LIGHTMAP 2
#define GLX_NORMAL 3
#define GLX_NORMALMATRIX 4
#define MC_MIDTEXCOORD 5
#define AT_TANGENT 6
#define NUMERIC_ID 7
#define GLX_COLOR 8
#define NORMALS_TEXTURE 9
#define SPECULAR_TEXTURE 10
#define GLX_VERTEX 11
#define PLAYER_POS 12
#define WORLD_POS 13
#define VIEW_POS 14
#define SHADOW_VIEW_POS 15
#define SHADOW_SAMPLE_POS 16
#define SHADOWCOLOR0 17
#define PROGRAM_ID 18
#define GBUFFER_DEBUG NOTHING //What to draw in gbuffers_textured. For CONSTANT, see the key in the zip file. [NOTHING LMCOORD LIGHTMAP GLX_NORMAL GLX_NORMALMATRIX MC_MIDTEXCOORD AT_TANGENT GLX_COLOR NORMALS_TEXTURE SPECULAR_TEXTURE GLX_VERTEX PLAYER_POS WORLD_POS VIEW_POS SHADOW_VIEW_POS SHADOW_SAMPLE_POS SHADOWCOLOR0 NUMERIC_ID PROGRAM_ID]
#define COLOR_WEIGHT 0.75 //Mix level which combines the grayscale texture with the thing being debugged [0.0 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 0.95 1.00]